### ISSUE TITLE
pyls completion not working

### ISSUE THREAD

**Issue by incoggnito** [haorenW1025/completion-nvim#46] opened 2020-04-29 09:24 UTC
I've tried the following with a minimal example.
`nvim -u test.vim pyproj/test.py`

test.vim:
```vim
let g:python3_host_prog = '/home/inco/.pyenv/shims/python'
call plug#begin('~/.vim/plugged') 
    Plug 'neovim/nvim-lsp'
    Plug 'haorenW1025/completion-nvim'
call plug#end()
lua require'nvim_lsp'.pyls.setup{on_attach=require'completion'.on_attach}
au Filetype python setl omnifunc=v:lua.vim.lsp.omnifunc
" Use <Tab> and <S-Tab> to navigate through popup menu
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"

" Set completeopt to have a better completion experience
set completeopt=menuone,noinsert,noselect
```

Checkhealth tells me plys and everything else works.
I've created a virtual environment for neovim. Maybe it helps to reproduce what's wrong.

ArchLinux specific:
```sh
# pacman -S pyenv
yay -S pyenv-virtualenv
```

Create and activate virtual environment for python 3.7

```sh
pyenv install 3.7.7
pyenv virtualenv 3.7.7 neovim3
pyenv activate neovim3
```

Install related packages for neovim and pyls
```sh
pip install --upgrade pip
pip install neovim
pip install 'python-language-server[all]'
pip install -U setuptools
pip install pyls-mypy pyls-isort pyls-black
python -m pyls --help
which python
```

Add the vitrual python path to the neovim host config
```vim
let g:python3_host_prog = '/home/inco/.pyenv/shims/python'
```

When i type no autocompletion starts.
I guess `import` should already expandable on `imp`.

PS: When i use your current configuration the completion on .vim files works perfectly.

**Comment by haorenW1025** [comment] 2020-04-29 14:09
Hmm that's very weird cause I can't reproduce and I don't know why...
![Kapture 2020-04-29 at 20 42 04](https://user-images.githubusercontent.com/35623968/80597222-1effed00-8a5a-11ea-928c-55cbe79d2114.gif)

**Comment by incoggnito** [comment] 2020-04-30 06:59
It seems there no LSP-client attached to the buffer.
`:lua print(vim.inspect(vim.lsp.buf_get_clients()))`
return {}

**Comment by haorenW1025** [comment] 2020-04-30 09:55
Yeah I think this issue may comes from `nvim_lsp` cause it seems like the LSP-client is not correctly attached. Closing this for now, feel free to reopen it for any updates.

**Closed by haorenW1025** 2020-04-30 09:55 UTC
