### ISSUE TITLE
Column value outside range

### ISSUE THREAD

**Issue by kristijanhusak** [haorenW1025/completion-nvim#52] opened 2020-05-02 06:57 UTC
Hi,

I think this is an upstream issue in neovim's lsp, but maybe you know what's exactly causing it.

I'm getting this error with `vimls`.

```
Error executing vim.schedule lua callback: /usr/local/share/nvim/runtime/lua/vim/lsp/util.lua:641: Column value outside range
```

I get it when I type this:
```
function! s:map_item()
```

Once I close the parenthesis (or auto pairs does that for me, I tried both), Error appears. Error continues to appear if i continue typing `abort`.

**Comment by haorenW1025** [comment] 2020-05-02 09:31
I traced the code a little bit, it seems like this error came from the diagnostic part. I use this config to disable the diagnostic and everything works fine. 
```vim
set runtimepath+=~/.vim/plugged/nvim-lsp
set runtimepath+=~/.vim/plugged/completion-nvim

lua require'nvim_lsp'.vimls.setup{on_attach=require'completion'.on_attach}
au Filetype vim setl omnifunc=v:lua.vim.lsp.omnifunc

" Set completeopt to have a better completion experience
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
set completeopt=menuone,noinsert,noselect

lua << EOF
  local callback = 'textDocument/publishDiagnostics'
  vim.lsp.callbacks[callback] = function(_, _, result, _)
    return
  end
EOF
```
I think this could be an issue of `neovim` or `vimls`, likely `vimls` though cause this cannot be reproduced using other language server.

**Comment by kristijanhusak** [comment] 2020-05-02 16:28
I'm not getting this result with coc, so I'm not sure if it's vimls. It could potentially be nvim's lsp.

**Comment by haorenW1025** [comment] 2020-05-05 09:11
Okay I guess I've found out the cause of this issue. This comes from the function `highlight_range` from `runtime/lua/vim/lsp/util.lua`. The function was used to create underline and various highlight for the diagnostic part of lsp. The code is as follow
```lua
local function highlight_range(bufnr, ns, hiname, start, finish)
  if start[1] == finish[1] then
    -- TODO care about encoding here since this is in byte index?
    api.nvim_buf_add_highlight(bufnr, ns, hiname, start[1], start[2], finish[2])
  else
    api.nvim_buf_add_highlight(bufnr, ns, hiname, start[1], start[2], -1)
    for line = start[1] + 1, finish[1] - 1 do
      api.nvim_buf_add_highlight(bufnr, ns, hiname, line, 0, -1)
    end
    api.nvim_buf_add_highlight(bufnr, ns, hiname, finish[1], 0, finish[2])
  end
end
```
However, `vimls` sometimes return weird values. The `start[2]` and `finish[2]` should be the column number but `start[2]` will be -1 in some condition of `vimls`. coc must have handled this issue and it should be fixed easily adding a condition like `if start[2] < 0 then return end`

**Comment by kristijanhusak** [comment] 2020-05-05 09:54
I'll leave link to your comment on the neovim issue where i reported it. Thanks for figuring it out.

**Comment by haorenW1025** [comment] 2020-05-06 03:00
Okay, I'm closing this on my side though.

**Closed by haorenW1025** 2020-05-06 03:00 UTC
