### ISSUE TITLE
Completion menu not displaying

### ISSUE THREAD

**Issue by michaeljoelphillips** [haorenW1025/completion-nvim#51] opened 2020-05-02 05:56 UTC
I'm attempting to make the switch from `deoplete-lsp` to this plugin (nice work, by the way), but I'm having some difficulties getting completion working.

In a mostly clean (no plugins, some config) runtime of nvim `v0.5.0-482-ga6071ac04`, the completion menu doesn't appear as I type.  I have verified that I have an attached client, unlike the problem described in #46, and I can confirm that my language server is sending responses to completion requests.  There are two things that I notice:
1. The completion trigger characters aren't being loaded from the language server, despite them being present when I call `:lua print(vim.inspect(vim.lsp.buf_get_clients()))`
2. If I manually set the completion trigger characters, the completion list fails to parse with the following error:`Error executing vim.schedule lua callback: shared.lua:486: s: expected string, got userdata`

This particular language server works with `deoplete-lsp` and another VSCode client, but just in case it could be useful, the completion response is attached below.

If I can provide more info please let me know.
```
Content-Type: application/vscode-jsonrpc; charset=utf8
Content-Length: 4292

{"id":10,"result":{"isIncomplete":false,"items":[{"label":"getUri","kind":2,"detail":"public getUri(): string","documentation":"","sortText":null,"filterText":null,"insertText":"getUri","textEdit":null,"additionalTextEdits":null,"command":null,"data":null,"insertTextFormat":1},{"labe
l":"getSource","kind":2,"detail":"public getSource(): string","documentation":"","sortText":null,"filterText":null,"insertText":"getSource","textEdit":null,"additionalTextEdits":null,"command":null,"data":null,"insertTextFormat":1},{"label":"getNodes","kind":2,"detail":"public getNod
es(): array","documentation":"\/**\n * @return NodeAbstract[]\n *\/","sortText":null,"filterText":null,"insertText":"getNodes","textEdit":null,"additionalTextEdits":null,"command":null,"data":null,"insertTextFormat":1},{"label":"getNodesAtCursor","kind":2,"detail":"public getNodesAtC
ursor(LanguageServer\\CursorPosition $cursorPosition): array","documentation":"\/**\n * @return NodeAbstract[]\n *\/","sortText":null,"filterText":null,"insertText":"getNodesAtCursor","textEdit":null,"additionalTextEdits":null,"command":null,"data":null,"insertTextFormat":1},{"label"
:"getNodesBesideCursor","kind":2,"detail":"public getNodesBesideCursor(LanguageServer\\CursorPosition $cursorPosition): array","documentation":"\/**\n * @return NodeAbstract[]\n *\/","sortText":null,"filterText":null,"insertText":"getNodesBesideCursor","textEdit":null,"additionalText
Edits":null,"command":null,"data":null,"insertTextFormat":1},{"label":"getClassName","kind":2,"detail":"public getClassName(): string","documentation":"","sortText":null,"filterText":null,"insertText":"getClassName","textEdit":null,"additionalTextEdits":null,"command":null,"data":nul
l,"insertTextFormat":1},{"label":"getMethod","kind":2,"detail":"public getMethod(string $methodName): PhpParser\\Node\\Stmt\\ClassMethod","documentation":"","sortText":null,"filterText":null,"insertText":"getMethod","textEdit":null,"additionalTextEdits":null,"command":null,"data":nul
l,"insertTextFormat":1},{"label":"getClassProperty","kind":2,"detail":"public getClassProperty(string $propertyName): PhpParser\\Node\\Stmt\\Property","documentation":"","sortText":null,"filterText":null,"insertText":"getClassProperty","textEdit":null,"additionalTextEdits":null,"comm
and":null,"data":null,"insertTextFormat":1},{"label":"findNodes","kind":2,"detail":"public findNodes(string $class): array","documentation":"\/**\n * @return NodeAbstract[]\n *\/","sortText":null,"filterText":null,"insertText":"findNodes","textEdit":null,"additionalTextEdits":null,"c
ommand":null,"data":null,"insertTextFormat":1},{"label":"searchNodes","kind":2,"detail":"public searchNodes(callable $criteria): array","documentation":"\/**\n * @return NodeAbstract[]\n *\/","sortText":null,"filterText":null,"insertText":"searchNodes","textEdit":null,"additionalText
Edits":null,"command":null,"data":null,"insertTextFormat":1},{"label":"getUseStatements","kind":2,"detail":"public getUseStatements(): array","documentation":"\/**\n * @return NodeAbstract[]\n *\/","sortText":null,"filterText":null,"insertText":"getUseStatements","textEdit":null,"add
itionalTextEdits":null,"command":null,"data":null,"insertTextFormat":1},{"label":"getConstructorNode","kind":2,"detail":"public getConstructorNode(): PhpParser\\Node\\Stmt\\ClassMethod","documentation":"","sortText":null,"filterText":null,"insertText":"getConstructorNode","textEdit":
null,"additionalTextEdits":null,"command":null,"data":null,"insertTextFormat":1},{"label":"getNamespace","kind":2,"detail":"public getNamespace(): string","documentation":"","sortText":null,"filterText":null,"insertText":"getNamespace","textEdit":null,"additionalTextEdits":null,"comm
and":null,"data":null,"insertTextFormat":1},{"label":"getCursorPosition","kind":2,"detail":"public getCursorPosition(int $line, int $character): LanguageServer\\CursorPosition","documentation":"\/**\n * Calculate the cursor position relative to the beginning of the file.\n *\n * This
 method removes all characters proceeding the $character at $line\n * and counts the total length of the final string.\n *\/","sortText":null,"filterText":null,"insertText":"getCursorPosition","textEdit":null,"additionalTextEdits":null,"command":null,"data":null,"insertTextFormat":1}
]},"error":null,"jsonrpc":"2.0"}Content-Type: application/vscode-jsonrpc; charset=utf8
```

**Comment by haorenW1025** [comment] 2020-05-02 06:13
Hmm have you tried the minimal config in [here](https://github.com/haorenW1025/completion-nvim/wiki/trouble-shooting), it seems to me that you haven't set the lsp up with the `on_attach` function.

**Comment by michaeljoelphillips** [comment] 2020-05-02 07:13
Yes, here is my config.
```
call plug#begin('~/.local/share/nvim/plugged')
    Plug 'michaeljoelphillips/nvim-lsp', { 'dir': '/home/nomad/Code/nvim-lsp' }
    Plug 'haorenW1025/completion-nvim'
call plug#end()

lua require'nvim_lsp'.phpls.setup{on_attach=require'completion'.on_attach}
au Filetype php setl omnifunc=v:lua.vim.phpls.omnifunc

" Use <Tab> and <S-Tab> to navigate through popup menu
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"

" Set completeopt to have a better completion experience
set completeopt=menuone,noinsert,noselect
```

This is the [debug log](https://github.com/haorenW1025/completion-nvim/files/4567236/vim-debug.txt):
```
{ {
    _on_attach = <function 1>,
    callbacks = <1>{
      ["window/logMessage"] = <function 2>,
      ["window/showMessage"] = <function 3>,
      ["workspace/configuration"] = <function 4>
    },
    cancel_request = <function 5>,
    config = {
      _on_attach = <function 6>,
      callbacks = <table 1>,
      capabilities = {}
    },
    ... OPEN TO SEE MORE ...
} }
```

This is my `nvim-lsp` config:
```
local configs = require 'nvim_lsp/configs'
local util = require 'nvim_lsp/util'
local lsp = vim.lsp

local server_name = "phpls"

configs[server_name] = {
  default_config = {
    cmd = {"php", "-d", "memory_limit=256M", "/usr/local/bin/phpls"};
    filetypes = {"php"};
    root_dir = util.root_pattern("composer.lock", ".git");
    log_level = lsp.protocol.MessageType.Warning;
    settings = {};
  };
}
-- vim:et ts=2 sw=2
```

**Comment by haorenW1025** [comment] 2020-05-02 08:20
Okay, I'll try to reproduce it. It might take some time since I've never worked with php before... Can you also check if this issue only occurs in `phpls`? Also where should I can the `phpls` language server?

**Comment by michaeljoelphillips** [comment] 2020-05-03 05:41
Just tested with `gopls` and a config similar to the above and it is working.  `phpls` is an unreleased language server that I am actively working on.  I can get a repro codebase setup for you with a build of `phpls` if it would help debugging.  The only requirement would be a box running PHP 7.4.

In the meantime, I did some more debugging.  It seems that completion is working on _some_ items.  For example, `$this->` would not complete, but `$this->logger->` did complete.  Both cases work normally using other language clients.  In the first example, I got the error that I mentioned above in the first post, but in the second I did not.  In both cases, I had to manually set the trigger characters.

![image](https://user-images.githubusercontent.com/530807/80899494-5d094500-8cd6-11ea-97d3-255575ea32b2.png)

Attached is a more verbose log of both the requests and the responses between this plugin and `phpls`: [output.log](https://github.com/haorenW1025/completion-nvim/files/4569677/output.log)

**Comment by michaeljoelphillips** [comment] 2020-05-03 05:53
I'm not sure if this is helpful, [but this appears to be the line of code in `runtime/lua/vim/shared.lua` that is producing the error message](https://github.com/neovim/neovim/blob/d13c1642ae9c966b7e32779b7aacb7b2eb1f1cee/runtime/lua/vim/shared.lua#L493):

```
if not vim.is_callable(t) then  -- Check type name.
  if (not optional or val ~= nil) and not _is_type(val, _type_name(t)) then
    error(string.format("%s: expected %s, got %s", param_name, _type_name(t), type(val)))
  end
elseif not t(val) then  -- Check user-provided validation function.
  error(string.format("%s: expected %s, got %s", param_name, (spec[3] or '?'), val))
end
...
```

**Comment by michaeljoelphillips** [comment] 2020-05-03 07:01
I have discovered the problem.  `completion-nvim` is failing when there are properties (LSP `CompletionItemKind.Property`) in the completion list.  Here is a formatted example of a property returned in a completion list:
```
{
    "additionalTextEdits": null,
    "command": null,
    "data": null,
    "detail": "",
    "documentation": "",
    "filterText": null,
    "insertText": null,
    "insertTextFormat": null,
    "kind": 10,
    "label": "thisPropertyBreaksCompletion",
    "sortText": null,
    "textEdit": null
}
```

Here is an asciinema of the issue:
https://asciinema.org/a/WqQ6CVlRf6BEZZvQhAhNqBsgo

**Comment by michaeljoelphillips** [comment] 2020-05-03 07:12
Here is a repo for debugging.  Everything you need to reproduce the issue should be in here.  If you have difficulty, please let me know.

https://github.com/michaeljoelphillips/completion-nvim-repro

**Comment by haorenW1025** [comment] 2020-05-03 11:16
Thank you so much for the information! Unfortunately I'm kind of busy this several days, will try to reproduce it in my spare time. Thanks!

**Comment by clason** [comment] 2020-05-03 11:24
@michaeljoelphillips Can you reproduce this with the default omnicompletion (`:set omnifunc=v:lua.vim.lsp.omnifunc`)?

**Comment by clason** [comment] 2020-05-03 11:54
On a related note, I think customization of `kind` should be a feature of base neovim (not just for completionItemKind but also for symbolKind) and done as part of the server configuration (i.e., it should be server-specific). I am planning on opening an issue at the neovim repo(s) soon.

**Comment by michaeljoelphillips** [comment] 2020-05-03 19:55
@haorenW1025, no rush.  Thanks for your interest in this issue.

@clason, I have the same issue with setting that omnifunc value.

**Comment by haorenW1025** [comment] 2020-05-05 08:47
Sorry for pending this so long, I've tested it and here's the result.
1. The problem will still be able to reproduce without `completion-nvim`(using omni-func), so this should actually be an issue of neovim.
2. In the neovim source code, here the code for parsing the return items to a completion word
```lua
local function get_completion_word(item)
  if item.textEdit ~= nil and item.textEdit.newText ~= nil then
    return item.textEdit.newText
  elseif item.insertText ~= nil then
    return item.insertText
  end
  return item.label
end
```
However, after some testing, I've found out `phpls` return `vim.NIL` for `item.textEdit` and `item.insertText`. So it will pass the condition but break the `complete` function(which show the completion-menu). There are also some PR([here](https://github.com/neovim/neovim/pull/12237)) to handle `vim.NIL` before.
A simple proof is I've changed the `get_completion_word(item)` function of `completion-nvim` to let it handle `vim.NIL` and the completion works.
![Kapture 2020-05-05 at 16 44 14](https://user-images.githubusercontent.com/35623968/81048920-cdd77980-8eef-11ea-8b84-f533c5ba6a8c.gif)

I can push my fix in `completion-nvim` first but still the issue should be solve in the neovim side.

**Comment by michaeljoelphillips** [comment] 2020-05-09 05:51
Thank you for looking into the issue, @haorenW1025.  That PR was merged, so I will test with the latest nightly build and see if that resolves the problem.

**Comment by haorenW1025** [comment] 2020-05-09 06:33
I think the PR I mentioned was not aimed to solve this issue. Maybe you have to open another issue in neovim.

**Comment by haorenW1025** [comment] 2020-05-10 16:37
I've push my fix in completion-nvim, close it on my side.

**Closed by haorenW1025** 2020-05-10 16:37 UTC
