### ISSUE TITLE
Arguments navigation

### ISSUE THREAD

**Issue by zegervdv** [haorenW1025/completion-nvim#58] opened 2020-05-08 20:28 UTC
Is there a way to navigate the arguments of a function that are completed?

For example for python `itertools.chain` completes to:
```
itertools.chain(${1:*iterables})${0}
```

Is there a way to, after triggering completion, to move the cursor to each of the arguments? Similar to how it works for UltiSnips?

If not, can the arguments be disabled. 
As it is now it takes more time to clean up than having no completion. :)

Thanks for the nice plugin!

**Comment by haorenW1025** [comment] 2020-05-09 04:03
1. Those are the snippets which LSP returns and we're currently working on another engine that can parse it correctly. Will notify you when it's stable enough:)
2. May I ask what language server you use in python? Cause I can't reproduce it using both `pyls` and `pyls_ms`

**Comment by zegervdv** [comment] 2020-05-09 08:23
Great to hear :)

I am using `pyls`:
```
Name: python-language-server
Version: 0.25.0
Summary: Python Language Server for the Language Server Protocol
Home-page: https://github.com/palantir/python-language-server
Author: Palantir Technologies, Inc.
Author-email: None
License: UNKNOWN
Location: /usr/local/lib/python3.6/dist-packages
Requires: pluggy, jedi, future, python-jsonrpc-server
Required-by:
```

Tested with your minimal config.

**Comment by haorenW1025** [comment] 2020-05-09 09:13
Hmm very weird cause I can't reproduce...I'm using this minimal config, but I update pyls to the latest version though.
```vim
call plug#begin('~/.vim/plugged') 
    Plug 'neovim/nvim-lsp'
    Plug 'haorenW1025/completion-nvim'
call plug#end()
lua require'nvim_lsp'.pyls.setup{on_attach=require'completion'.on_attach}
au Filetype python setl omnifunc=v:lua.vim.lsp.omnifunc
" Use <Tab> and <S-Tab> to navigate through popup menu
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"

" Set completeopt to have a better completion experience
set completeopt=menuone,noinsert,noselect
```
![Kapture 2020-05-09 at 17 11 34](https://user-images.githubusercontent.com/35623968/81469589-51f36f00-9218-11ea-94f1-c80ed60aa0d6.gif)

**Comment by zegervdv** [comment] 2020-05-09 11:05
yes, just tried it with the latest version (0.31.10) and it does not happen there.
Should have tried that first :)

**Comment by haorenW1025** [comment] 2020-05-09 12:13
Okay nice, will close this for now.

**Closed by haorenW1025** 2020-05-09 12:13 UTC

**Comment by illotum** [comment] 2020-06-09 03:28
Hi! I get this problem with the latest (v0.4.1) `gopls`
![lsp](https://user-images.githubusercontent.com/1162134/84102814-4c7b7700-a9c6-11ea-8c98-4278ce2738b1.gif)

Did you make any headway on the other engine?

**Comment by Xuyuanp** [comment] 2020-08-18 15:14
I get this problem too, with gopls(v0.4.4)
