### ISSUE TITLE
Next second or third completeopt item breaks completeopt popup menu

### ISSUE THREAD

**Issue by nacknime-official** [haorenW1025/completion-nvim#106] opened 2020-06-06 19:50 UTC
**My testing minimal init.vim (with completion-nvim)**
```
call plug#begin('~/.vim/plugged') 
    Plug 'neovim/nvim-lsp'
    Plug 'haorenW1025/completion-nvim'
call plug#end()
lua require'nvim_lsp'.pyls_ms.setup{on_attach=require'completion'.on_attach}
au Filetype lua setl omnifunc=v:lua.vim.lsp.omnifunc
" Use <Tab> and <S-Tab> to navigate through popup menu
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
" Set completeopt to have a better completion experience
set completeopt=menuone,noinsert,noselect
```

**My testing minimal init.vim (without completion-nvim)**
```
call plug#begin('~/.vim/plugged') 
    Plug 'neovim/nvim-lsp'
call plug#end()
lua require'nvim_lsp'.pyls_ms.setup{}
au Filetype python setl omnifunc=v:lua.vim.lsp.omnifunc
" Use <Tab> and <S-Tab> to navigate through popup menu
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
" Set completeopt to have a better completion experience
set completeopt=menuone,noinsert,noselect
```

**How to reproduce**
I've seen it after updating all plugins via `:PlugUpdate`. There were nvim-lsp and completion-nvim updates, so I don't know which commit might break it.
The video below can show you that issue. test.vim is with completion-nvim
https://youtu.be/dmRWn-jD8Zc
Without completion-nvim it works via omnifunc and there's no issue.

**Comment by carlosgarciafm** [comment] 2020-06-06 21:52
I tried rolling back `completion-nvim` to the commit 03af7f8 and it seemed to fix the issue.
Could you try doing the same to corroborate?
 Since you're using vim-plug, you can specify a commit for with:
`Plug 'haorenW1025/completion-nvim', { 'commit': '03af7f8' }`.

**Comment by haorenW1025** [comment] 2020-06-07 03:26
I've revert back some changes and it seems to work fine now. Please update and check:)

**Comment by carlosgarciafm** [comment] 2020-06-07 04:43
That fixes the issue. Thanks!

**Comment by haorenW1025** [comment] 2020-06-07 05:46
Close this for now, feel free to reopen if anything goes wrong!

**Closed by haorenW1025** 2020-06-07 05:46 UTC

**Comment by nacknime-official** [comment] 2020-06-07 13:12
Hello. After updating to the last update for now I got a new issue like this. 
It doesn't show the completeopt popup menu with the **My testing minimal init.vim (with completion-nvim)**. I can only call omnifunc complete menu by pressing <C-x><C-o>. Watch the video below
https://youtu.be/xfHbMWTc5dg

**Comment by haorenW1025** [comment] 2020-06-07 13:40
@nacknime-official That's strange cause it works on my side... Can you enter the command `:autocmd InsertEnter`  and see if there is a augroup `CompletionCommand  InsertEnter`? Also can you try with `pyls` instead?

**Comment by nacknime-official** [comment] 2020-06-07 16:22
> @nacknime-official That's strange cause it works on my side... Can you enter the command `:autocmd InsertEnter` and see if there is a augroup `CompletionCommand InsertEnter`? Also can you try with `pyls` instead?
```

:autocmd InsertEnter                                                                                                                                                                                     
--- Autocommands ---
CompletionCommand  InsertEnter
    <buffer=1>
              lua require'completion'.on_InsertEnter()
```
`pyls` doesn't work the same as `pyls_ms`, but there're nothing even in omnifunc completion. I think I should write my hardware:
Archlinux with sway(wayland)
Neovim's `:checkhealth` with **My testing minimal init.vim (with completion-nvim)** - https://hastebin.com/lacukosagu
Python 3.8.3

**Comment by haorenW1025** [comment] 2020-06-07 16:33
It seems super weird for me...Some method worth trying is
1. go back to previous commit and see if it works?
2. Try other language server(other than python).
2. delete your `view` files(normally in `~/.local/share/nvim/view`)
2. rebuild neovim
Also you can open up a new issue if you want. Sorry for the inconvenience:(

**Comment by nacknime-official** [comment] 2020-06-07 16:36
I tried downgrade to the `03af7f8` adding` { 'commit': '03af7f8' }` after the plugin declaration and... that works!

**Comment by haorenW1025** [comment] 2020-06-07 17:23
Yeah I think bfcb99a breaks it. I've reverted the changes upstream. Please update and see if it works. Thanks!

**Comment by nacknime-official** [comment] 2020-06-07 17:49
> Yeah I think [bfcb99a](https://github.com/haorenW1025/completion-nvim/commit/bfcb99a7f143e1835fa47c93afce5a20ea7d2845) breaks it. I've reverted the changes upstream. Please update and see if it works. Thanks!

Yes, it works! Thank you for amazing plugin!

**Comment by haorenW1025** [comment] 2020-06-07 17:56
@nacknime-official Thank you for help finding the cause! Hopefully this kind of issue won't happen again:)
